### ISSUE TITLE
404 while trying to access publications at the FIS of the University of Bamberg

### ISSUE THREAD

**Issue by sebastian-lempert** [kianschmalenbach/rdf-browser#15]
Looks like the RDF Browser has some problems with the Forschungsinformationssystem (FIS) of the University of Bamberg. For example if you try to access this publication https://fis.uni-bamberg.de/handle/uniba/46530 with Firefox while the RDF Browser plugin is activated you will end up with an URL https://fis.uni-bamberg.de/rdf/46530/turtle and an error message "404 - Resource not found".

This seems to be true for all publications listed in the FIS. E.g. looks you won't be able to access any of the publications from this list https://fis.uni-bamberg.de/cris/rp/rp01358/publications.html while the RDF Browser is activated within Firefox.

**Comment by aharth** [comment]
The issue seems to be with the server.

With:

$ curl --header "Accept: text/turtle" -v https://fis.uni-bamberg.de/handle/uniba/46530

the server returns a redirect to

https://fis.uni-bamberg.de/rdf/46530/turtle

which leads to a 404.

Rather than adding a workaround in RDF browser, I would advise a WONTFIX.

The Uni Bamberg people should fix their server setup instead.

**Comment by kianschmalenbach** [comment]
Hi,
+1 for WONTFIX from my side as of Andreas' analysis. If I don't hear anything the next days, I will therefore close the issue.

**Comment by sebastian-lempert** [comment]
True, my fault. I'll close this issue.
