### ISSUE TITLE
Breaks on RDFa on http://xmlns.com/foaf/spec/

### ISSUE THREAD

**Issue by kernc** [kianschmalenbach/rdf-browser#23]
The addon breaks on RDFa-annotated page like: http://xmlns.com/foaf/spec/
In addition, the browser tab (Firefox 78.6esr) _crashes_ on URL: view-source:http://xmlns.com/foaf/spec/.

**Comment by kianschmalenbach** [comment]
Hi,
Thanks for your feedback! I cannot reproduce the example that the Add-on breaks on the page [http://xmlns.com/foaf/spec/](http://xmlns.com/foaf/spec/). Moreover, since the view-source tab is not controlled by the Add-on, fixing this is not possible within the Add-on code. You might want to file a Firefox bug report for this.

Cheers,
Kian
