### ISSUE TITLE
Quick Actions keep unchecked

### ISSUE THREAD

**Issue by MattesWhite** [kianschmalenbach/rdf-browser#26]
To test my JSON-LD I often turned the `Qucik Actions` off and on again to switch between the actual JSON and RDF browser's _Turtle view_. However, it seems that this way I broke the plug-in. If I check all the boxes in `Quick Actions` they turn off again after reloading a page.

I already re-installed the plug-in and rebooted firefox and my PC, nothing helped. For several days now I can no longer use the RDF browser.

**Comment by kianschmalenbach** [comment]
Hi,
I have not seen or experienced this behavior before. Could you go to _about:addons_ and click RDF Browser to see what the current version is? If it is not 1.2.0, I recommend updating the plugin by clicking the gear wheel on top and select "Check for updates". Afterwards, go to the settings section and click "Restore default". If this does not help fixing the issue, we can dig deeper to figure out what the problem is.

Cheers,
Kian

**Comment by MattesWhite** [comment]
Okay after repeated re-installation I dug into my local firefox files. Via content search I found entries in `storage-sync.sqlite` and `storage-sync-v2.sqlite` which I removed before I installed the add-on again. Surprise, it worked. I'm still not sure what happened...

However, problem solved...
